### ISSUE TITLE
Console Command Line options

### ISSUE THREAD

**Issue by OzBob** [MisterJames/LemonadeStand#1]
extend the Command line version of the game to use:
https://github.com/dotnet/command-line-api/blob/main/docs/Syntax-Concepts-and-Parser.md
options and parameters, e.g. 
drinkstand.exe --playername "bob" --basemodifier 0.2344

or older versions for the command line extension:
https://docs.microsoft.com/en-us/archive/msdn-magazine/2016/september/essential-net-command-line-processing-with-net-core-1-0
https://dotnetnew.azurewebsites.net/template/lazyWombat.Console.Commands.Template/lazyWombat.Console.Commands

**Comment by MisterJames** [comment]
Great idea! I have to think about the impact of the base modifier, but would you like to tackle the name in a PR?

**Comment by OzBob** [comment]
future note: terrajobst talking to jon sequeira: demoing system.commandline with commands:
https://youtu.be/kM0pWAwo_FQ?t=250

**Comment by OzBob** [comment]
great vid on "[Command Line Parameter Suggestions with DragonFruit]( https://www.youtube.com/watch?v=sQt69IkJmd8) ([#250](https://www.youtube.com/hashtag/250))" by @MisterJames 

Info to install and enable suggestions shell:
[https://github.com/dotnet/command-lin...](https://github.com/dotnet/command-line-api/blob/main/docs/dotnet-suggest.md)
