### ISSUE TITLE
share latest branch

### ISSUE THREAD

**Issue by OzBob** [MisterJames/LemonadeStand#2]
Nice Monster Vid: https://www.youtube.com/watch?v=z_gX90DfLfg

Can you share/publish the latest 'src' to your ['console' branch](https://github.com/MisterJames/LemonadeStand/tree/console-version)?

I can see a few changes going on here:
https://github.com/MisterJames/LemonadeStand/commit/97c744e2e3ca9055ebfe27b9d10d085f88b63626

**Comment by MisterJames** [comment]
You bet, thanks @OzBob . I was just tidying a few things up and would be happy to share it out today.

**Comment by MisterJames** [comment]
@OzBob Latest code is up! Remember...it's a work in progress 😁
